### ISSUE TITLE
reuse secret across stacks?

### ISSUE THREAD

**Issue by networkpadawan** [binxio/cfn-secret-provider#18]
Is it possible to reuse secrets/keys on different stacks?

At the moment I Get:
Custom::Secret CREATE_FAILED Failed to create resource. An error occurred (ParameterAlreadyExists) when calling the PutParameter operation: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.
the use case is that I would like to reuse the value for redshift cfn template where I can destroy a redshift cluster with a  deletepolicy of Snapshot and rebuild adding a reference to said snapshot.

**Comment by mvanholsteijn** [comment]
Currently, Custom::Secret does not allow you to do this.
