### ISSUE TITLE
make the private Key downloadable

### ISSUE THREAD

**Issue by aerioeus** [binxio/cfn-secret-provider#23]
Hi, so far evth is working nicely,  the only thing I cant do is using the keypair I have generated to ssh into an EC2 instance since I cannot download the private key. Could you add this feature please. merci

**Comment by mvanholsteijn** [comment]
@aerioeus , you can easily "download" to key through ssm:

```
aws ssm  --query Parameter.Value ---output text get-parameter --name $PARAMETER_NAME --with-decryption
```

**Comment by aerioeus** [comment]
merci,  but i produces no result:

```
xxx@machine1: xxx (master) $ aws ssm  --query Parameter.Value --output text get-parameters --name EC2KeyPair --with-decryption
None   
```

**Comment by mvanholsteijn** [comment]
you are using get-parameters not get-parameter (singular).

**Comment by aerioeus** [comment]
Merci,  which parameter do I need to use in order to get the key.pem - since I guess Parameter.Value needs to be replaced

**Comment by mvanholsteijn** [comment]
remove the s from get-parameters.... If you insist on calling get-parameters (plural)  change your query to Parameters[0].Value

**Comment by aerioeus** [comment]
sorry, somehow thats not gonna work:

```
xxx@machine1: xxx (master) $ aws ssm --query Parameters[0].Value --output text get-parameters --name ECSKeyPair --with-decryption
None
xxx@machine1: xxx (master) $ aws ssm --query Parameters[0].Value --output text get-parameters --name ec2-key --with-decryption
None
xxx@machine1: xxx (master) $ aws ssm --query Parameter.Value --output text get-parameters --name ec2-key --with-decryption
None
```

But the keys exist of course

![image](https://user-images.githubusercontent.com/23232503/46950217-51b6e000-d084-11e8-89c1-38f668f22e80.png)

**Comment by mvanholsteijn** [comment]
@aerioeus please, for the love of god, use get-parameter. Not get-parameters.

**Comment by mvanholsteijn** [comment]
please use exactly as I said:

```
aws ssm get-parameter --name $NAME --with-decryption --output text --query Parameter.Value
```

**Comment by aerioeus** [comment]
sorry for being so clumsy, but it doesnt work:
Thats my cfn-code:
```
  CustomPrivateKey:
    Type: Custom::RSAKey
    Properties:
      Name: "/dev/private-key"
      KeyAlias: alias/aws/ssm
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-secret-provider'

  ECSKeyPair:
    Type: Custom::KeyPair
    DependsOn: CustomPrivateKey
    Properties:
      Name: ECSKeyPair
      PublicKeyMaterial: !GetAtt 'PrivateKey.PublicKey'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-secret-provider'
```
so I assume the correct line to download the .pem file would be:

```
aws ssm get-parameter --name CustomPrivateKey --with-decryption --output text --query Parameter.Value
```
but that only yields an error...

**Comment by mvanholsteijn** [comment]
You have specified the name of your private key in the SSM parameter store as "/dev/private-key". Use that name to retrieve the value from SSM:
```
aws ssm get-parameter --name /dev/private-key --with-decryption --output text --query Parameter.Value
```

**Comment by aerioeus** [comment]
Merci, finally It worked. Great, sorry my incompetence in this case. I appreciate very much you taking your time to guide me through it. 
One final question: the download begins with:
```
-----BEGIN PRIVATE KEY-----
ˋˋˋ

whereas any ˋkeypair.pemˋ I have download begins with‘

```
-----BEGIN RSA PRIVATE KEY-----
....
ˋˋˋ
Do I need to adjust that or doesn’t it matter for using the key to SSH into EC2 Instances?

Again much obliged Mark‘

Andreas

**Comment by mvanholsteijn** [comment]
@aerioeus, it does not matter for ssh'ing into the ec2 machines. 

The '-----BEGIN RSA PRIVATE KEY----' is the traditional OpenSSL format. The ` '-----BEGIN PRIVATE KEY----' is the new PKCS8 format.

**Comment by aerioeus** [comment]
merci for your patience!
