### ISSUE TITLE
Failed to create resource. No module named '_cffi_backend'

### ISSUE THREAD

**Issue by walkerlangley** [binxio/cfn-secret-provider#31]
Hey,

I just updated a template I've been using from version 0.13.3 to 1.0.0 but got the error message below when trying to create a resource with cloudformation that calls this function. Rolling the function back to v0.13.3 worked, but given AWS lambda's sunsetting support for python < v3 I'd like update our template to use your v1.0.0.

Have you run into this error before or having any idea how to resolve it? Thanks in advance!

**Failed to create resource. No module named '_cffi_backend'**

**Comment by mvanholsteijn** [comment]
change the version and set the  lambda runtime to python3.7 too.
