### ISSUE TITLE
Generate your own copy of the lambda zip file

### ISSUE THREAD

**Issue by jedis00** [binxio/cfn-secret-provider#36]
Hello,

How does one go about generating our own copy of the lambda zip file? I've pulled it down, but don't see a way to download all of the dependencies instead of using the prepackaged version.

Thank you!

**Comment by mvanholsteijn** [comment]
just type `make` in the directory. It will build the zipfile through Docker and copy the end result in the `target/` directory.

**Comment by tfarmer00** [comment]
@mvanholsteijn Thank you! Can I suggest adding that to the README?
