### ISSUE TITLE
RSAKey 'Description' field does not accept a purely numeric string.

### ISSUE THREAD

**Issue by MNiedzielski** [binxio/cfn-secret-provider#4]
On RSAKey, the 'Description' field does not accept a purely numeric string.

`Failed to update resource. invalid resource properties: 20180131 is not of type 'string' Failed validating 'type' in schema['properties']['Description']: {'default': '', 'description': 'the description of the key in the parameter store', 'type': 'string'} On instance['Description']: 20180131`

As RSAKey does not provide the Version attribute from the resource, our plan was to use Description to version keys using a date string.

Thanks.

**Comment by mvanholsteijn** [comment]
I see where this problem is caused. I will fix this for you.

**Comment by mvanholsteijn** [comment]
I am reading your issue again. Although the 'bug' is there, I think you would like to do something else.

Are you referring to the version of the parameter in the store? Do  you want it as a attribute that can be retrieved using Fn::GetAtt?

```
    "Parameters": [
        {
            "KeyId": "alias/aws/ssm",
            "Name": "/mysecret",
            "LastModifiedDate": 1516274490.292,
            "Value": "5XMgHcoAD3g9c0kDrL5spMbHybvNw+6uvk6kZpE5byyIbwR9RA==",
            "Version": 1,
            "LastModifiedUser": "arn:aws:iam:::user/mvanholsteijn",
            "Type": "SecureString"
        }
    ]
```

**Comment by mvanholsteijn** [comment]
@MNiedzielski version 0.8.3 of the secret provider returns 'Version' attribute which is the version of the value in the parameter store.

Note that it  is NOT related to the input 'Version'.

Is this oke?

**Comment by MNiedzielski** [comment]
This is great!  Thank you.
