### ISSUE TITLE
Override function name

### ISSUE THREAD

**Issue by kornicameister** [binxio/cfn-secret-provider#40]
Hello,

In the first place, thx for awesome function. It helped us a lot with setting up a cluster that required SSH communication.
However, we do have a slight request.

We would like to utilize this part as a sub-stack to as a stack where we need `cfn-secret-provider`. That obviously mean we may have more than one copy of the function in the region which is impossible as your lambad do have a fixed name.
Would it be possible to provide both **input** and **output** to simply have it deployed.

**Comment by mvanholsteijn** [comment]
Hi Kornica, Why not solve this in your own copy of the cfn template? I like to keep the sample templates as simple as possible.

**Comment by kornicameister** [comment]
Copy is an option, just forking is not as simple as straightforward even if you license with Apache.
Anyway, thx for the comment. I am not forcing nor asking to fix it. I get your point regarding simplicity.

@pklimczak please see if we can actually fork and deal with the problem internally, thx :+1: 
@mvanholsteijn Closing for now. Perhaps later in the future we might get back to if someone express a similar need.

**Comment by mvanholsteijn** [comment]
Would it help if you would have a more permissive license? If so, which one do you need?

**Comment by kornicameister** [comment]
Its not a point of license 🙂. License is Ok TBH.
Anyway, we have decided for single global deployment. It was a reasonable tradeoff for now.

thx for help anyway and good Łuck 👌
