### ISSUE TITLE
error deploying latest cloud formation version 1.4.1

### ISSUE THREAD

**Issue by cnpeyt** [binxio/cfn-secret-provider#51]
I receive this error during create from cloud formation against 1.4.1 of the template

Received response status [FAILED] from custom resource. Message returned: ModuleNotFoundError: No module named '_cffi_backend' (RequestId: 472fd2b4-9388-47ff-aa06-2306297316ea)

**Comment by mvanholsteijn** [comment]
Hi @cnpeyt sorry that I had to put you through this. I know have updated all Python version references in the source and did an integration test deployment. version 1.4.3 works fine.

**Comment by cnpeyt** [comment]
great, i'll give it a try right now

**Comment by cnpeyt** [comment]
@mvanholsteijn worked nicely this time!!!  thanks for the quick fix!
