### ISSUE TITLE
cleanup on delete

### ISSUE THREAD

**Issue by cnpeyt** [binxio/cfn-secret-provider#53]
I'm not sure if this is bug or not.  I'm using Custom::RSAKey to generate a public/private key pair, the private key is being written to SSM parameter store.  When I deleted the stack, the SSM param that was created to store the private key was not removed.  Should the resource on cleanup in turn remove the SSM param as well?

**Comment by mvanholsteijn** [comment]
The ssm parameter in which the key is stores should be deleted. Did the delete fail for some reason? The provider tends to ignore errors on delete.

**Comment by cnpeyt** [comment]
So I don't know what happened for sure.  I deleted the stack and I thought everything was removed successfully.  I noticed later that the SSM param for the private key still existed.  I'll try again this week and see if can reproduce.
