### ISSUE TITLE
When trying to use Python 3.9 runtime as being new corporate requirement due to 3.8 vulnerabilities getting cff errors. 

### ISSUE THREAD

**Issue by arkrud** [binxio/cfn-secret-provider#60]
While creating Private Key in CloudFormation Received response status [FAILED] from custom resource. Message returned: ModuleNotFoundError: No module named '_cffi_backend' (RequestId: 3860dfd8-3261-4bbc-a634-73a89c468287)

**Comment by mvanholsteijn** [comment]
Hi @arkrud, thank you for opening an issue. Which version are you using? Versions >= 2.0.0 of the provider are built for the Python3.9 runtime. 

Please reopen if the problem persists.

**Comment by arkrud** [comment]
I tried it with version 2.0.1 and Python3.9 and get same error:
Received response status [FAILED] from custom resource. Message returned: ModuleNotFoundError: No module named '_cffi_backend' (RequestId: 3bda91a4-ffdd-418b-a2a4-8769a04c6fe3)

**Comment by arkrud** [comment]
Hi Mark,

 

I tried with 2.0.1 and 39 but it failed again with same error.

I commented on the issue in Git, but I cannot reopen it.

 

Sincerely,

 

Arkadiy Rudin

**Comment by arkrud** [comment]
Hi,

I see error in us-east-1

Ark

**Comment by arkrud** [comment]
I noticed that I changed the reference to zip release v2.0.1 only in one place in CF temple. 
When I updated it in both locations it is working now.
So you can close the issue.

Thank You,

Arkadiy
