### ISSUE TITLE
Ship the SecretProviders up to pypi

### ISSUE THREAD

**Issue by spockNinja** [binxio/cfn-secret-provider#7]
I am currently using your cfn-resource-provider base in my organization's custom resource provider, and it's great!

I would like to add the `SecretProvider` to my own lambda function, but not all of the others in this repository. For me, the ideal situation would be add another pip install requirement for `cfn-secret-provider` and then be able to import just the ones I want into my own lambda function.

If this isn't something you would like to do, I can certainly copy-paste the ones I want as a workaround.

Thanks!

**Comment by mvanholsteijn** [comment]
Hi @spockNinja,

I have not thought about that, but I am certainly willing to put the providers in pypi. It might even be a better way of creating my lambdas. First a module and than a plain install the lambda container :-)

As soon as I find the time, I will refactor the source structure build system to implement your suggestion.

Cheers,
Mark

**Comment by mvanholsteijn** [comment]
Hi @spockNinja, I decided not to go for this approach right now. I have many providers by now, and it is just to much hassle to go through.
